name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
              
    steps:
    - uses: actions/checkout@v2
    
    - name: Set SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short ${{ github.sha }})"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}  
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-rest-api:${{ sha_short }}
                        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: algan/go-rest-api:${{ sha_short }}
