name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - uses: actions/checkout@v2
      with:
        ref: aligandi-go-rest-api
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}


    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-rest-api:$(date +%s)
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: algan/go-rest-api:$(date +%s)
